# Generated by Django 4.2.5 on 2023-12-11 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('about_text', models.TextField(blank=True, null=True)),
                ('yelp_url', models.URLField(unique=True)),
                ('menu_url', models.URLField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('phone_area_code', models.CharField(max_length=5)),
                ('phone_number', models.CharField(max_length=20)),
                ('offers_delivery', models.BooleanField(default=False)),
                ('offers_takeout', models.BooleanField(default=False)),
                ('offers_catering', models.BooleanField(default=False)),
                ('reservations', models.BooleanField(default=False)),
                ('accepts_credit_cards', models.BooleanField(default=False)),
                ('accepts_cash', models.BooleanField(default=False)),
                ('accepts_android_pay', models.BooleanField(default=False)),
                ('accepts_apple_pay', models.BooleanField(default=False)),
                ('private_parking', models.BooleanField(default=False)),
                ('waiter_service', models.BooleanField(default=False)),
                ('free_wifi', models.BooleanField(default=False)),
                ('full_bar', models.BooleanField(default=False)),
                ('wheelchair_accessible', models.BooleanField(default=False)),
                ('tv', models.BooleanField(default=False)),
                ('open_to_all', models.BooleanField(default=False)),
                ('outdoor_seating', models.BooleanField(default=False)),
                ('dogs_allowed', models.BooleanField(default=False)),
                ('bike_parking', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_location', models.CharField(max_length=255)),
                ('user_follower_count', models.IntegerField(default=0)),
                ('user_review_count', models.IntegerField(default=0)),
                ('user_photo_count', models.IntegerField(default=0)),
                ('comment_text', models.TextField()),
                ('rating', models.FloatField()),
                ('reactions_useful', models.IntegerField(default=0)),
                ('reactions_funny', models.IntegerField(default=0)),
                ('reactions_cool', models.IntegerField(default=0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.business')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=9)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='scraper.business')),
            ],
        ),
    ]
