# Generated by Django 4.2.5 on 2023-12-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_comment_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
