# Generated by Django 4.2.5 on 2023-12-14 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_alter_business_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_text',
            new_name='user_comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_follower_count',
            new_name='user_friends',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_photo_count',
            new_name='user_photos',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='rating',
            new_name='user_rating',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_review_count',
            new_name='user_reviews',
        ),
    ]
